fetch_currency:
  cron: '*/5 * * * *'
  class: 'CurrencyWorker'
fetch_history_currency:
  cron: '0 0 * * *'
  class: 'HistoryCurrencyWorker'
fetch_bid_ask_currency:
  cron: '*/5 * * * *'
  class: 'BidAskCurrencyWorker'
fetch_user_bid_ask_currency:
  cron: '*/5 * * * *'
  class: 'UserBidAskCurrencyWorker'
